// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"chat-backend/internal/app"
	"chat-backend/internal/app/command"
	"chat-backend/internal/infrastructure/persistence"
	"chat-backend/internal/interfaces/http"
	"chat-backend/internal/interfaces/ws"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB, rdb *redis.Client) (*app.App, func(), error) {
	repository := persistence.NewUserRepository(db, rdb)
	authHandler := command.NewAuthHandler(repository)
	httpAuthHandler := http.NewAuthHandler(authHandler)
	userHandler := command.NewUserHandler(repository)
	httpUserHandler := http.NewUserHandler(userHandler)
	roomRepository := persistence.NewRoomRepository(db, rdb)
	roomHandler := command.NewRoomHandler(roomRepository)
	httpRoomHandler := http.NewRoomHandler(roomHandler, db)
	chatRepository := persistence.NewMessageRepository(db)
	messageHandler := command.NewMessageHandler(chatRepository)
	hub := ws.NewHub(chatRepository, roomRepository, repository, rdb)
	httpMessageHandler := http.NewMessageHandler(messageHandler, hub)
	routerOptions := http.RouterOptions{
		AuthHandler:    httpAuthHandler,
		UserHandler:    httpUserHandler,
		RoomHandler:    httpRoomHandler,
		MessageHandler: httpMessageHandler,
		Hub:            hub,
	}
	engine := http.NewRouter(routerOptions)
	appApp := app.NewApp(engine, hub)
	return appApp, func() {
	}, nil
}
